<#
.SYNOPSIS
    callisto-jupiter one-command installer (Windows).

.DESCRIPTION
    Creates a dedicated venv under %ProgramData%\callisto-jupiter\venv, writes the
    config, and installs + starts the service via NSSM when nssm is on PATH. If
    nssm is missing, performs the install + config and prints the remaining steps.
    Re-running is safe (existing config is backed up).

.EXAMPLE
    # Run from an elevated PowerShell, in the repo root:
    .\setup.ps1 "https://ingest.callistosignal.com/<id>?token=<token>"

    The DSN may also come from $env:CALLISTO_DSN, or you'll be prompted.
#>
[CmdletBinding()]
param(
    [string]$Dsn
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$DataDir   = Join-Path $env:ProgramData 'callisto-jupiter'
$Venv      = Join-Path $DataDir 'venv'
$Bin       = Join-Path $Venv 'Scripts\callisto-jupiter.exe'
$Config    = Join-Path $DataDir 'config.toml'

function Say  ($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Ok   ($m) { Write-Host "OK  $m" -ForegroundColor Green }
function Die  ($m) { Write-Host "ERR $m" -ForegroundColor Red; exit 1 }

# --- admin check -----------------------------------------------------------------
$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Die "Run this from an elevated PowerShell (Run as Administrator)."
}

# --- resolve DSN: param -> env -> prompt ------------------------------------------
if (-not $Dsn) { $Dsn = $env:CALLISTO_DSN }
if (-not $Dsn) { $Dsn = Read-Host "Paste the server DSN (from the server page in Callisto)" }
if ($Dsn -notmatch '^https://.*token=') {
    Die "DSN looks wrong. Expected: https://ingest.callistosignal.com/<id>?token=<token>"
}

# --- require python 3.9+ ---------------------------------------------------------
$py = Get-Command py -ErrorAction SilentlyContinue
if (-not $py) { $py = Get-Command python -ErrorAction SilentlyContinue }
if (-not $py) { Die "Python not found. Install Python 3.9+ first." }
& $py.Source -c "import sys; sys.exit(0 if sys.version_info >= (3,9) else 1)"
if ($LASTEXITCODE -ne 0) { Die "Python 3.9+ required." }

# --- venv + install (GPU autodetect) ---------------------------------------------
New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
Say "Creating virtualenv at $Venv ..."
& $py.Source -m venv $Venv
$Pip = Join-Path $Venv 'Scripts\pip.exe'
& $Pip install --quiet --upgrade pip

if (Get-Command nvidia-smi -ErrorAction SilentlyContinue) {
    Say "NVIDIA GPU detected — installing with GPU support (pynvml)..."
    & $Pip install --quiet "$ScriptDir[gpu]"
} else {
    Say "No NVIDIA GPU detected — installing core (CPU/RAM/DISK)..."
    & $Pip install --quiet "$ScriptDir"
}

# --- write config (back up any existing one) -------------------------------------
if (Test-Path $Config) {
    Say "Existing config found — backing up to $Config.bak"
    Copy-Item $Config "$Config.bak" -Force
}
@"
# callisto-jupiter configuration — generated by setup.ps1
# The DSN embeds a secret push token; keep this file private.
dsn = "$Dsn"
interval_seconds = 60
disk_path = "C:\\"
timeout_seconds = 10
"@ | Set-Content -Path $Config -Encoding UTF8
Ok "Config written to $Config"

# --- install + start service via NSSM --------------------------------------------
$nssm = Get-Command nssm -ErrorAction SilentlyContinue
if ($nssm) {
    Say "Installing service via NSSM..."
    & nssm install callisto-jupiter $Bin
    & nssm set callisto-jupiter AppDirectory $DataDir
    & nssm set callisto-jupiter Start SERVICE_AUTO_START
    & nssm set callisto-jupiter AppStdout (Join-Path $DataDir 'agent.log')
    & nssm set callisto-jupiter AppStderr (Join-Path $DataDir 'agent.err.log')
    & nssm start callisto-jupiter
    Ok "Service 'callisto-jupiter' installed and started."
    Write-Host "    Status: nssm status callisto-jupiter"
} else {
    Say "nssm not found on PATH — install + config done; finish the service step manually:"
    Write-Host "    Download nssm.exe from https://nssm.cc/download, put it on PATH, then:" -ForegroundColor Yellow
    Write-Host "    nssm install callisto-jupiter `"$Bin`""
    Write-Host "    nssm set callisto-jupiter AppDirectory `"$DataDir`""
    Write-Host "    nssm set callisto-jupiter Start SERVICE_AUTO_START"
    Write-Host "    nssm start callisto-jupiter"
    Write-Host "    (see deploy\windows-nssm.md for details)"
}

# --- verify ----------------------------------------------------------------------
Say "Verifying with one collect + push cycle..."
& $Bin --once
if ($LASTEXITCODE -eq 0) {
    Ok "callisto-jupiter verified."
} else {
    Die "Test cycle failed — check the DSN and network."
}
