#!/usr/bin/env bash
#
# callisto-jupiter one-command installer (Linux + macOS).
#
# Usage:
#   sudo ./setup.sh "https://ingest.callistosignal.com/<id>?token=<token>"
#
# The DSN can also come from the CALLISTO_DSN environment variable, or you'll be
# prompted for it. Installs a dedicated venv at /opt/callisto-jupiter, writes the
# config to the OS-conventional path, installs + starts the service, and runs one
# verification cycle. Re-running is safe (venv reused, existing config backed up).
#
set -euo pipefail

VENV=/opt/callisto-jupiter
BIN="$VENV/bin/callisto-jupiter"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m✅ %s\033[0m\n' "$*"; }
err()  { printf '\033[1;31m❌ %s\033[0m\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

# --- 1. privilege: re-exec under sudo if not root --------------------------------
if [ "$(id -u)" -ne 0 ]; then
    say "Elevating with sudo..."
    exec sudo -E DSN_FROM_PARENT="${1:-${CALLISTO_DSN:-}}" bash "$0" "$@"
fi

# --- 2. resolve OS ---------------------------------------------------------------
case "$(uname -s)" in
    Linux)  OS=linux ;  CONFIG_DIR=/etc/callisto-jupiter ;;
    Darwin) OS=macos ;  CONFIG_DIR="/Library/Application Support/callisto-jupiter" ;;
    *)      die "Unsupported OS '$(uname -s)'. Use setup.ps1 on Windows." ;;
esac
CONFIG="$CONFIG_DIR/config.toml"

# --- 3. resolve DSN: arg → env (incl. sudo-forwarded) → prompt --------------------
DSN="${1:-${CALLISTO_DSN:-${DSN_FROM_PARENT:-}}}"
if [ -z "$DSN" ]; then
    printf 'Paste the server DSN (from the server page in Callisto): '
    read -r DSN
fi
case "$DSN" in
    https://*token=*) : ;;
    *) die "DSN looks wrong. Expected: https://ingest.callistosignal.com/<id>?token=<token>" ;;
esac

# --- 4. require python3 >= 3.9 ---------------------------------------------------
command -v python3 >/dev/null 2>&1 || die "python3 not found. Install Python 3.9+ first."
python3 - <<'PY' || die "Python 3.9+ required (found $(python3 -V 2>&1))."
import sys
sys.exit(0 if sys.version_info >= (3, 9) else 1)
PY

# --- 5. venv + install (GPU autodetect) ------------------------------------------
say "Creating virtualenv at $VENV ..."
python3 -m venv "$VENV"
"$VENV/bin/pip" install --quiet --upgrade pip

if command -v nvidia-smi >/dev/null 2>&1; then
    say "NVIDIA GPU detected — installing with GPU support (pynvml)..."
    "$VENV/bin/pip" install --quiet "$SCRIPT_DIR[gpu]"
else
    say "No NVIDIA GPU detected — installing core (CPU/RAM/DISK)..."
    "$VENV/bin/pip" install --quiet "$SCRIPT_DIR"
fi

# --- 6. write config (back up any existing one) ----------------------------------
DISK_PATH="/"
mkdir -p "$CONFIG_DIR"
if [ -f "$CONFIG" ]; then
    say "Existing config found — backing up to $CONFIG.bak"
    cp "$CONFIG" "$CONFIG.bak"
fi
cat > "$CONFIG" <<EOF
# callisto-jupiter configuration — generated by setup.sh
# The DSN embeds a secret push token; keep this file private.
dsn = "$DSN"
interval_seconds = 60
disk_path = "$DISK_PATH"
timeout_seconds = 10
EOF
chmod 600 "$CONFIG"
ok "Config written to $CONFIG"

# --- 7. install + start the service ----------------------------------------------
if [ "$OS" = linux ]; then
    say "Installing systemd service..."
    cp "$SCRIPT_DIR/deploy/callisto-jupiter.service" /etc/systemd/system/
    systemctl daemon-reload
    systemctl enable --now callisto-jupiter
    LOG_HINT="journalctl -u callisto-jupiter -f"
else
    say "Installing launchd daemon..."
    PLIST=/Library/LaunchDaemons/com.callistosignal.jupiter.plist
    cp "$SCRIPT_DIR/deploy/com.callistosignal.jupiter.plist" "$PLIST"
    chown root:wheel "$PLIST"
    launchctl bootout system/com.callistosignal.jupiter 2>/dev/null || true
    launchctl bootstrap system "$PLIST"
    launchctl kickstart -k system/com.callistosignal.jupiter
    LOG_HINT="tail -f /var/log/callisto-jupiter.log"
fi

# --- 8. verify with one collect+push cycle ---------------------------------------
say "Verifying with one collect + push cycle..."
if "$BIN" --once; then
    ok "callisto-jupiter installed and running."
    echo "   Follow logs: $LOG_HINT"
else
    die "Service installed but the test cycle failed — check the DSN and network, then: $LOG_HINT"
fi
